// Datamodel + data voor vastgoedkantoren. Gemigreerd van de live /kantoor/-pagina's
// (echte kantoren). Leads komen centraal binnen via het Elfsight-formulier, niet per kantoor.
// Uit te breiden met nieuwe kantoren of te koppelen aan een databron/CMS in fase 2.

export type Kantoor = {
  slug: string; // voor /kantoor/<slug>
  naam: string;
  makelaar?: string; // naam van de verantwoordelijke makelaar
  gemeente: string;
  provincie: string;
  provincieSlug?: string; // koppelt naar /vastgoedkantoren/<provincie> indien die pagina bestaat
  intro: string;
  diensten: string[];
  regios: string[]; // gebieden/gemeenten waar het kantoor actief is
  adres?: string;
  postcode?: string;
  telefoon?: string;
  email?: string;
  website?: string;
  bivNummer?: string; // BIV-erkenningsnummer
  bivHouder?: string; // persoon of onderneming bij wie het nummer hoort
  bivBron?: string; // pagina waarop het kantoor zijn wettelijke gegevens publiceert
  bivGecontroleerdOp?: string; // ISO-datum van de laatste handmatige controle
  foto?: string; // lokaal pad onder /afbeeldingen/kantoren/
  googlePlaceId?: string; // Google Place ID voor het ophalen van reviews
  premium?: boolean; // premium partner: toont overal een badge
  toegevoegdOp?: string; // ISO-datum voor sortering in het kantooroverzicht
  seoTitle?: string;
  seoDescription?: string;
};

export const kantoren: Kantoor[] = [
  {
    slug: "we-invest-demervallei",
    premium: true,
    googlePlaceId: "ChIJMdrZH6E7wUcRHc8DgINnwCk",
    naam: "We Invest Demervallei",
    makelaar: "Niels Wouters",
    gemeente: "Halen",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "We Invest Demervallei is een vastgoedkantoor in Paal (Beringen) in de provincie Limburg, onder leiding van makelaar Niels Wouters. Het kantoor begeleidt eigenaars en kopers bij de verkoop, verhuur en schatting van vastgoed in de regio Halen, Herk-de-Stad, Lummen, Beringen en Diest.",
    diensten: ["Woning verkopen", "Verhuur", "Gratis schatting", "Aankoopbegeleiding"],
    regios: ["Halen", "Herk-de-Stad", "Lummen", "Beringen", "Diest"],
    adres: "Koepoortstraat 6/3",
    postcode: "3545",
    telefoon: "0488 33 81 47",
    email: "demervallei@weinvest.be",
    website: "https://weinvest.be/nl-BE/agencies/demervallei/62",
    bivNummer: "514218",
    bivHouder: "Niels Wouters",
    bivBron: "https://weinvest.be/nl-BE/agencies/demervallei/62",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/we-invest-demervallei.svg", // SVG-namaak; echt logo mag dit vervangen
  },
  {
    slug: "hillewaere-vastgoed",
    googlePlaceId: "ChIJs2Zk0uSzxkcRLDfihV8Xm30",
    naam: "Hillewaere Vastgoed",
    gemeente: "Turnhout",
    provincie: "Antwerpen",
    provincieSlug: "antwerpen",
    intro:
      "Hillewaere Vastgoed is een vastgoedkantoor gevestigd in Turnhout dat zich richt op de verkoop en verhuur van residentieel en professioneel vastgoed. Het kantoor is actief in de provincies Antwerpen, Limburg en Oost-Vlaanderen en biedt daarnaast nieuwbouwbegeleiding, gratis waardebepaling en advies rond investeringsvastgoed.",
    diensten: ["Verkoop en verhuur", "Nieuwbouw en ontwikkeling", "Investerings- en bedrijfsvastgoed", "Gratis waardebepaling", "Hippisch vastgoed en luxe segment"],
    regios: ["Antwerpen", "Limburg", "Oost-Vlaanderen"],
    adres: "Parklaan 46",
    postcode: "2300",
    telefoon: "014 45 10 11",
    email: "vastgoed@hillewaere.be",
    website: "https://www.hillewaere-vastgoed.be/",
    bivNummer: "501935",
    bivBron: "https://www.hillewaere-vastgoed.be/",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/hillewaere-vastgoed.jpg",
  },
  {
    slug: "heylen-vastgoed",
    googlePlaceId: "ChIJg_99rDtSwUcR_MU0CVQhg_s",
    naam: "Heylen Vastgoed",
    gemeente: "Herentals",
    provincie: "Antwerpen",
    provincieSlug: "antwerpen",
    intro:
      "Heylen Vastgoed is een vastgoedkantoor met een vestiging aan de Grote Markt in Herentals, in de provincie Antwerpen. Het kantoor begeleidt klanten bij verkoop, verhuur, nieuwbouw, vastgoedbeheer en schatting en is actief in Vlaanderen.",
    diensten: ["Verkoop", "Verhuur", "Nieuwbouw", "Vastgoedbeheer", "Schatting", "Juridische ondersteuning"],
    regios: ["Herentals", "Antwerpen", "Vlaanderen"],
    adres: "Grote Markt 8-10",
    postcode: "2200",
    telefoon: "0800 29 223",
    email: "info@heylenvastgoed.be",
    website: "https://www.heylenvastgoed.be",
    bivNummer: "502895",
    bivBron: "https://www.heylenvastgoed.be",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/heylen-vastgoed.jpg",
  },
  {
    slug: "vastgoed-michoel",
    googlePlaceId: "ChIJY-Cs74TEw0cRXRCfGGvekcA",
    naam: "Vastgoed Michoel",
    gemeente: "Puurs-Sint-Amands",
    provincie: "Antwerpen",
    provincieSlug: "antwerpen",
    intro:
      "Vastgoed Michoel is een erkend vastgoedkantoor in Puurs-Sint-Amands in de provincie Antwerpen. Het kantoor is actief in Puurs, Liezele, Hingene en de omliggende regio Klein-Brabant, met diensten voor verkoop, verhuur, nieuwbouw en advies.",
    diensten: ["Verkoop", "Verhuur", "Nieuwbouw", "Advies"],
    regios: ["Puurs", "Liezele", "Hingene", "Klein-Brabant", "Scheldeland"],
    adres: "Hoogstraat 35",
    postcode: "2870",
    website: "https://vastgoedmichoel.be/nl",
    bivNummer: "507422",
    bivHouder: "Pauline Michoel",
    bivBron: "https://vastgoedmichoel.be/nl",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/vastgoed-michoel.jpg",
  },
  {
    slug: "immo-de-prins",
    googlePlaceId: "ChIJq6qqqhqMw0cR5Ot3BvG9W9o",
    naam: "Immo De Prins",
    gemeente: "Sint-Niklaas",
    provincie: "Oost-Vlaanderen",
    intro:
      "Immo De Prins is een vastgoedkantoor in Sint-Niklaas, in de provincie Oost-Vlaanderen. Het kantoor is actief in het Waasland met verkoop, verhuur, vastgoedbeheer en waardebepaling.",
    diensten: ["Verkoop", "Verhuur", "Vastgoedbeheer", "Advies op maat", "Waardebepaling", "Begeleiding notariële akte"],
    regios: ["Waasland", "Sint-Niklaas"],
    adres: "Mercatorstraat 64",
    postcode: "9100",
    telefoon: "03 776 06 55",
    email: "info@immodeprins.be",
    website: "https://immodeprins.be/",
    bivNummer: "200392",
    bivHouder: "Lieven De Prins",
    bivBron: "https://immodeprins.be/contact",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/immo-de-prins.jpg",
  },
  {
    slug: "immo-plees",
    googlePlaceId: "ChIJVaXGapY6wUcRxZ-BNzOHHqc",
    naam: "Immo Plees",
    gemeente: "Heusden-Zolder",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Immo Plees is een familiaal vastgoedkantoor dat actief is in de regio van Beringen tot Heusden-Zolder in de provincie Limburg. Het kantoor begeleidt klanten bij de verkoop en verhuur van woningen, appartementen en gronden en biedt een gratis waardebepaling aan.",
    diensten: ["Woning verkopen", "Verhuur", "Gratis waardebepaling", "Begeleiding projectontwikkelaars"],
    regios: ["Beringen", "Heusden-Zolder"],
    adres: "Sint-Willibrordusplein 19",
    postcode: "3550",
    telefoon: "011 23 30 44",
    email: "info@immoplees.be",
    website: "https://immoplees.be/",
    bivNummer: "507429",
    bivBron: "https://immoplees.be/nl/contact/",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/immo-plees.jpg",
  },
  {
    slug: "living-stone-dilbeek",
    googlePlaceId: "ChIJPxbahdPGw0cRimTjXHv69bA",
    naam: "Living Stone Dilbeek",
    gemeente: "Dilbeek",
    provincie: "Vlaams-Brabant",
    provincieSlug: "vlaams-brabant",
    intro:
      "Living Stone Dilbeek is een vastgoedkantoor gevestigd in Dilbeek dat instaat voor de verkoop, verhuur, schatting en het beheer van vastgoed. Het kantoor is actief in Vlaams-Brabant, Brussel en het Pajottenland en begeleidt eigenaars en kopers doorheen het volledige verkoop- en verhuurtraject.",
    diensten: ["Woning verkopen", "Verhuur", "Schatting", "Rentmeesterschap", "Nieuwbouwprojecten"],
    regios: ["Dilbeek", "Vlaams-Brabant", "Brussel", "Pajottenland"],
    adres: "Astridlaan 1",
    postcode: "1700",
    telefoon: "02 466 05 75",
    website: "https://living-stone.be/nl",
    bivNummer: "509622",
    bivBron: "https://living-stone.be/vastgoedhuizen/vastgoedhuis-dilbeek",
    bivGecontroleerdOp: "2026-07-28",
  },
  {
    slug: "coga-vastgoed",
    googlePlaceId: "ChIJRfK5ntkGxEcRwtn7cixwjq4",
    naam: "COGA Vastgoed",
    gemeente: "Brecht",
    provincie: "Antwerpen",
    provincieSlug: "antwerpen",
    intro:
      "COGA Vastgoed is een erkend vastgoedkantoor in Brecht (Sint-Job-in-'t-Goor) in de provincie Antwerpen. Het kantoor verzorgt verkoop, verhuur en schatting van vastgoed in Brecht en de omliggende regio tussen Antwerpen en de Nederlandse grens.",
    diensten: ["Woning verkopen", "Verhuur", "Schatting", "Nieuwbouwprojecten", "Projectbegeleiding", "Juridisch advies"],
    regios: ["Brecht", "Sint-Job-in-'t-Goor", "Regio Antwerpen"],
    adres: "Eikenlei 2 B",
    postcode: "2960",
    telefoon: "03 636 47 47",
    email: "info@coga.be",
    website: "https://coga.be/",
    bivNummer: "500559",
    bivHouder: "Koen Conings",
    bivBron: "https://coga.be/contact",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/coga-vastgoed.jpg",
  },
  {
    slug: "just-wonen",
    googlePlaceId: "ChIJXSNVjHW5xkcRd7-VBTJFf_U",
    naam: "Just Wonen",
    seoTitle: "Just Wonen Ravels: diensten, reviews en contact",
    seoDescription:
      "Bekijk Just Wonen in Ravels: diensten, BIV-erkenning, werkgebied, Google-reviews en contact voor verkoop, verhuur of een schatting.",
    gemeente: "Ravels",
    provincie: "Antwerpen",
    provincieSlug: "antwerpen",
    intro:
      "Just Wonen is een vastgoedkantoor gevestigd in de Kerkstraat in Ravels, dat verkoop en verhuur van woningen combineert met verzekeringen en financieel advies. Het kantoor is actief in Ravels en Poppel en begeleidt het volledige verhuurproces, inclusief kandidaatscreening en contractbeheer.",
    diensten: ["Woning verkopen", "Verhuur", "Schatting", "Kandidaatscreening", "Contractbeheer", "Verzekeringen", "Financieel advies"],
    regios: ["Ravels", "Poppel"],
    adres: "Kerkstraat 15",
    postcode: "2380",
    telefoon: "014 65 87 11",
    email: "info@justwonen.be",
    website: "https://www.justwonen.be/",
    bivNummer: "507005",
    bivHouder: "Sander Turelinckx",
    bivBron: "https://www.biv.be/vastgoedmakelaars/sander-turelinckx-507005",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/just-wonen.jpg",
  },
  {
    slug: "homerun",
    googlePlaceId: "ChIJX0Gk1ljpw0cRSLn857qo1WM",
    naam: "Homerun Real Estate",
    gemeente: "Grimbergen",
    provincie: "Vlaams-Brabant",
    provincieSlug: "vlaams-brabant",
    intro:
      "Homerun Real Estate is een vastgoedkantoor gevestigd in Grimbergen in Vlaams-Brabant. Het kantoor begeleidt eigenaars bij de verkoop en schatting van woningen en verzorgt onder meer asbestattesten.",
    diensten: ["Woning verkopen", "Schatting", "Asbestattest"],
    regios: ["Grimbergen"],
    adres: "Molenstraat 93",
    postcode: "1851",
    telefoon: "02 445 10 00",
    email: "contact@homerun.immo",
    website: "https://www.homerun.immo/",
    bivNummer: "512774",
    bivHouder: "Bart Narmon",
    bivBron: "https://www.homerun.immo/nl/contact",
    bivGecontroleerdOp: "2026-07-28",
    foto: "/afbeeldingen/kantoren/homerun.jpg",
  },
  {
    slug: "swevers-real-estate",
    googlePlaceId: "ChIJBanmhN07wUcR23s35e1OFp0",
    toegevoegdOp: "2026-09-01",
    naam: "Swevers Real Estate",
    makelaar: "Marc Swevers",
    seoTitle: "Swevers Real Estate Beringen: diensten en contact",
    seoDescription:
      "Bekijk Swevers Real Estate in Beringen: diensten, BIV-erkenning, werkgebied en contact voor verkoop, aankoop of een schatting in Limburg.",
    gemeente: "Beringen",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Swevers Real Estate is een vastgoedkantoor met hoofdzetel in Beringen en vestigingen in Hasselt, Heusden-Zolder en Borgloon. Het kantoor begeleidt eigenaars en kopers bij verkoop, aankoop, schatting en vastgoedadvies in Limburg.",
    diensten: ["Woning verkopen", "Aankoopbegeleiding", "Gratis schatting", "Vastgoedadvies"],
    regios: ["Beringen", "Hasselt", "Heusden-Zolder", "Borgloon", "Limburg"],
    adres: "Hoogstraat 8",
    postcode: "3580",
    telefoon: "011 25 51 55",
    email: "immo@swevers.be",
    website: "https://www.swevers.be/",
    bivNummer: "502259",
    bivHouder: "Marc Swevers",
    bivBron: "https://www.biv.be/vastgoedmakelaars/marc-swevers-502259",
    bivGecontroleerdOp: "2026-09-01",
    foto: "/afbeeldingen/kantoren/swevers-real-estate.svg",
  },
  {
    slug: "axpertise-vastgoed-advies",
    googlePlaceId: "ChIJpy_T9yccwUcR1rjU_prgRHI",
    toegevoegdOp: "2026-09-01",
    naam: "AXPERTISE Vastgoed & Advies",
    makelaar: "Seppe Schaepkens",
    seoTitle: "AXPERTISE Vastgoed & Advies Borgloon: contact",
    seoDescription:
      "Bekijk AXPERTISE Vastgoed & Advies in Borgloon: contactgegevens, BIV-erkenning en begeleiding bij vastgoed in Limburg.",
    gemeente: "Borgloon",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "AXPERTISE Vastgoed & Advies is een vastgoedkantoor in Borgloon. Het kantoor vermeldt begeleiding bij de aan- en verkoop van vastgoed, waardebepalingen en plaatsbeschrijvingen.",
    diensten: ["Woning verkopen", "Woning kopen", "Waardebepaling", "Plaatsbeschrijving"],
    regios: ["Borgloon", "Tongeren-Borgloon", "Limburg"],
    adres: "Guldenbodemlaan 37",
    postcode: "3840",
    telefoon: "0471 22 00 95",
    email: "info@axpertise.be",
    website: "https://www.axpertise.be/",
    bivNummer: "508363",
    bivHouder: "Seppe Schaepkens",
    bivBron: "https://www.axpertise.be/",
    bivGecontroleerdOp: "2026-09-01",
    foto: "/afbeeldingen/kantoren/axpertise-vastgoed-advies.png",
  },
  {
    slug: "av-vastgoed",
    googlePlaceId: "ChIJI9LI_NzhwEcR1mdydLtcxG8",
    toegevoegdOp: "2026-09-01",
    naam: "AV Vastgoed",
    makelaar: "Adam Vandersmissen",
    seoTitle: "AV Vastgoed Hoeselt: contact en BIV-erkenning",
    seoDescription:
      "Bekijk AV Vastgoed in Hoeselt: contactgegevens, BIV-erkenning en diensten voor verkoop, verhuur en waardebepaling.",
    gemeente: "Hoeselt",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "AV Vastgoed is een vastgoedkantoor in Hoeselt. Het kantoor vermeldt begeleiding bij verkoop en verhuur, nieuwbouw en waardebepalingen.",
    diensten: ["Woning verkopen", "Woning verhuren", "Nieuwbouw", "Waardebepaling"],
    regios: ["Hoeselt", "Bilzen-Hoeselt", "Limburg"],
    adres: "Tongersesteenweg 50",
    postcode: "3730",
    telefoon: "089 23 50 55",
    email: "info@av-vastgoed.be",
    website: "https://av-vastgoed.be/",
    bivNummer: "501136",
    bivHouder: "Adam Vandersmissen",
    bivBron: "https://av-vastgoed.be/",
    bivGecontroleerdOp: "2026-09-01",
    foto: "/afbeeldingen/kantoren/av-vastgoed.png",
  },
  {
    slug: "claar-vastgoed",
    googlePlaceId: "ChIJNQJQwiwnwUcRkiqEnDUHBgY",
    toegevoegdOp: "2026-09-01",
    naam: "Claar Vastgoed",
    makelaar: "Pieter Claes",
    seoTitle: "Claar Vastgoed Zonhoven: contact en BIV-vermelding",
    seoDescription:
      "Bekijk Claar Vastgoed in Zonhoven: contactgegevens, BIV-vermelding en begeleiding bij verkoop, aankoop en waardebepaling.",
    gemeente: "Zonhoven",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Claar Vastgoed is een vastgoedkantoor in Zonhoven. Het kantoor vermeldt begeleiding bij de verkoop en aankoop van vastgoed en waardebepalingen.",
    diensten: ["Woning verkopen", "Woning kopen", "Waardebepaling"],
    regios: ["Zonhoven", "Limburg"],
    adres: "Dorpsplein 38",
    postcode: "3520",
    telefoon: "0493 40 11 74",
    email: "info@claarvastgoed.be",
    website: "https://claarvastgoed.be/",
    bivNummer: "514588",
    bivBron: "https://claarvastgoed.be/",
    bivGecontroleerdOp: "2026-09-01",
    foto: "/afbeeldingen/kantoren/claar-vastgoed.png",
  },
  {
    slug: "century21-immok-sint-truiden",
    googlePlaceId: "ChIJhyR1Mz0RwUcRJmY3GJQo8vU",
    toegevoegdOp: "2026-09-02",
    naam: "Century21 ImmoK Sint Truiden",
    seoTitle: "Century21 ImmoK Sint Truiden: diensten, reviews en contact",
    seoDescription:
      "Bekijk Century21 ImmoK Sint Truiden: diensten, werkgebied, beschikbare Google-reviews en contact voor verkoop, verhuur of een schatting.",
    gemeente: "Sint-Truiden",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Century21 ImmoK Sint Truiden is een vastgoedkantoor aan de Naamsevest in Sint-Truiden. Het kantoor is actief in Haspengouw en het Hageland en vermeldt begeleiding bij verkoop, verhuur, investeren en een online schatting.",
    diensten: ["Woning verkopen", "Verhuur", "Investeren", "Online schatting"],
    regios: ["Sint-Truiden", "Haspengouw", "Hageland"],
    adres: "Naamsevest 80",
    postcode: "3800",
    telefoon: "016 82 17 78",
    email: "info@immok.be",
    website: "https://www.century21.be/nl/kantoor/century-21-immo-k/dnHjCXoB5YVLjoN9cmYW",
    bivBron: "https://www.century21.be/nl/kantoor/century-21-immo-k/dnHjCXoB5YVLjoN9cmYW",
    bivGecontroleerdOp: "2026-09-02",
    foto: "/afbeeldingen/kantoren/century21-immok-sint-truiden.svg",
  },
  {
    slug: "era-connect",
    googlePlaceId: "ChIJu8Og7JLhwEcRGkR7-tqxOFI",
    toegevoegdOp: "2026-09-02",
    naam: "ERA Connect",
    makelaar: "Wouter Franssens",
    seoTitle: "ERA Connect Hoeselt: diensten, reviews en contact",
    seoDescription:
      "Bekijk ERA Connect in Hoeselt: diensten, BIV-vermelding, werkgebied, beschikbare Google-reviews en contact voor verkoop, verhuur of een schatting.",
    gemeente: "Hoeselt",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "ERA Connect is een vastgoedkantoor aan de Bilzersteenweg in Hoeselt. Het kantoor begeleidt klanten bij verkoop, verhuur, aankoop en waardebepaling in Hoeselt, Bilzen, Tongeren en Riemst.",
    diensten: ["Woning verkopen", "Verhuur", "Woning kopen", "Gratis waardebepaling"],
    regios: ["Hoeselt", "Bilzen", "Tongeren", "Riemst"],
    adres: "Bilzersteenweg 45B/B1",
    postcode: "3730",
    telefoon: "089 69 59 59",
    email: "wouter@eraconnect.be",
    website: "https://www.era.be/nl/era-connect",
    bivNummer: "513041",
    bivHouder: "Wouter Franssens",
    bivBron: "https://www.era.be/nl/era-connect/team",
    bivGecontroleerdOp: "2026-09-02",
    foto: "/afbeeldingen/kantoren/era-connect.svg",
  },
  {
    slug: "era-impact-maaseik",
    googlePlaceId: "ChIJpQlINYzJwEcRhKn60WcMlB0",
    toegevoegdOp: "2026-09-02",
    naam: "ERA IMPACT Maaseik",
    makelaar: "Jan Veestraeten",
    seoTitle: "ERA IMPACT Maaseik: diensten, reviews en contact",
    seoDescription:
      "Bekijk ERA IMPACT Maaseik: diensten, BIV-vermelding, beschikbare Google-reviews en contact voor verkoop, verhuur of waardebepaling.",
    gemeente: "Maaseik",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "ERA IMPACT Maaseik is een vastgoedkantoor aan de Bosstraat in Maaseik. Het kantoor vermeldt begeleiding bij aankoop, verkoop, verhuur, waardebepaling en plaatsbeschrijvingen.",
    diensten: ["Woning verkopen", "Verhuur", "Woning kopen", "Waardebepaling", "Plaatsbeschrijving"],
    regios: ["Maaseik", "Limburg"],
    adres: "Bosstraat 92",
    postcode: "3680",
    telefoon: "089 46 48 63",
    website: "https://www.era.be/nl/era-impact",
    bivNummer: "503763",
    bivHouder: "Jan Veestraeten",
    bivBron: "https://www.era.be/nl/era-impact/legale-informatie",
    bivGecontroleerdOp: "2026-09-02",
    foto: "/afbeeldingen/kantoren/era-impact-maaseik.svg",
  },
  {
    slug: "era-nobis-sint-truiden",
    googlePlaceId: "ChIJ3-7uXA4XwUcRFR6h2IqPZaQ",
    toegevoegdOp: "2026-09-03",
    naam: "ERA NOBIS Sint-Truiden",
    seoTitle: "ERA NOBIS Sint-Truiden: diensten, reviews en contact",
    seoDescription:
      "Bekijk ERA NOBIS in Sint-Truiden: diensten, BIV-vermelding, werkgebied, beschikbare Google-reviews en contact voor verkoop, verhuur of een waardebepaling.",
    gemeente: "Sint-Truiden",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "ERA NOBIS Sint-Truiden is een vastgoedkantoor aan Schurhoven in Sint-Truiden. Het kantoor biedt diensten voor verkoop, verhuur, aankoop en waardebepaling in Sint-Truiden en de omliggende regio.",
    diensten: ["Woning verkopen", "Verhuur", "Woning kopen", "Waardebepaling"],
    regios: ["Sint-Truiden", "Nieuwerkerken", "Limburg"],
    adres: "Schurhoven 40 bus 1",
    postcode: "3800",
    telefoon: "011 35 14 00",
    email: "nobis@era.be",
    website: "https://www.era.be/nl/era-nobis",
    bivNummer: "515801",
    bivHouder: "An Keijers",
    bivBron: "https://www.era.be/nl/era-nobis/legale-informatie",
    bivGecontroleerdOp: "2026-09-03",
    foto: "/afbeeldingen/kantoren/era-nobis-sint-truiden.svg",
  },
  {
    slug: "found-baker-properties-limburg",
    googlePlaceId: "ChIJ_2bwvgNFG4MR7Wb403jnpEE",
    toegevoegdOp: "2026-09-03",
    naam: "Found & Baker Properties Limburg",
    seoTitle: "Found & Baker Properties Limburg Hasselt: reviews en contact",
    seoDescription:
      "Bekijk Found & Baker Properties Limburg in Hasselt: BIV-vermelding, werkgebied, beschikbare Google-reviews en contact voor residentieel en exclusief vastgoed.",
    gemeente: "Hasselt",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Found & Baker Properties Limburg is een vastgoedkantoor aan de Guffenslaan in Hasselt. Het kantoor richt zich op residentieel en exclusief vastgoed in Limburg.",
    diensten: ["Residentieel vastgoed", "Exclusief vastgoed", "Vastgoedadvies"],
    regios: ["Hasselt", "Limburg"],
    adres: "Guffenslaan 15",
    postcode: "3500",
    telefoon: "011 96 60 00",
    email: "hasselt@found-baker.com",
    website: "https://www.found-baker.com/nl/limburg",
    bivNummer: "513410",
    bivHouder: "David Fonteyne",
    bivBron: "https://www.found-baker.com/nl/limburg",
    bivGecontroleerdOp: "2026-09-03",
    foto: "/afbeeldingen/kantoren/found-baker-properties-limburg.svg",
  },
  {
    slug: "het-bedrijfskantoor",
    googlePlaceId: "ChIJ6VtpimUtwUcRWLDqJ12bVD4",
    toegevoegdOp: "2026-09-03",
    naam: "Het Bedrijfskantoor",
    seoTitle: "Het Bedrijfskantoor Lommel: diensten, reviews en contact",
    seoDescription:
      "Bekijk Het Bedrijfskantoor in Lommel: diensten, BIV-vermelding, beschikbare Google-reviews en contact voor commercieel en industrieel vastgoed.",
    gemeente: "Lommel",
    provincie: "Limburg",
    provincieSlug: "limburg",
    intro:
      "Het Bedrijfskantoor is een vastgoedkantoor aan de Binnensingel in Lommel, gespecialiseerd in commercieel en industrieel vastgoed. Het kantoor begeleidt klanten bij de verkoop en verhuur van bedrijfsvastgoed.",
    diensten: ["Bedrijfsvastgoed verkopen", "Bedrijfsvastgoed verhuren", "Vastgoedadvies"],
    regios: ["Lommel", "Pelt", "Bree", "Limburg"],
    adres: "Binnensingel 70 bus 2",
    postcode: "3920",
    telefoon: "011 91 90 50",
    email: "info@bedrijfskantoor.be",
    website: "https://www.bedrijfskantoor.be/contact?kantoor=lommel",
    bivNummer: "505570",
    bivHouder: "Rutger Schildermans",
    bivBron: "https://www.bedrijfskantoor.be/contact?kantoor=lommel",
    bivGecontroleerdOp: "2026-09-03",
    foto: "/afbeeldingen/kantoren/het-bedrijfskantoor.png",
  },
];

export function getKantoor(slug: string): Kantoor | undefined {
  return kantoren.find((k) => k.slug === slug);
}

export function getKantoorSlugs(): string[] {
  return kantoren.map((k) => k.slug);
}
